/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { FutureEventCreateRequest } from '../../models/future-event-create-request';
import { FutureEventResponse } from '../../models/future-event-response';

export interface CreateFutureEvent$Params {
  body: FutureEventCreateRequest;
}

export function createFutureEvent(http: HttpClient, rootUrl: string, params: CreateFutureEvent$Params, context?: HttpContext): Observable<StrictHttpResponse<FutureEventResponse>> {
  const rb = new RequestBuilder(rootUrl, createFutureEvent.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<FutureEventResponse>;
    })
  );
}

createFutureEvent.PATH = '/api/future-events';
