/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { FutureEventResponse } from '../../models/future-event-response';

export interface GetAllFutureEvents$Params {
}

export function getAllFutureEvents(http: HttpClient, rootUrl: string, params?: GetAllFutureEvents$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<FutureEventResponse>>> {
  const rb = new RequestBuilder(rootUrl, getAllFutureEvents.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<FutureEventResponse>>;
    })
  );
}

getAllFutureEvents.PATH = '/api/future-events';
