/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { FutureEventResponse } from '../../models/future-event-response';

export interface GetFutureEvent$Params {
  id: string;
}

export function getFutureEvent(http: HttpClient, rootUrl: string, params: GetFutureEvent$Params, context?: HttpContext): Observable<StrictHttpResponse<FutureEventResponse>> {
  const rb = new RequestBuilder(rootUrl, getFutureEvent.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<FutureEventResponse>;
    })
  );
}

getFutureEvent.PATH = '/api/future-events/{id}';
