/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ProjectionResponse } from '../../models/projection-response';

export interface GetProjections$Params {
  months?: number;
}

export function getProjections(http: HttpClient, rootUrl: string, params?: GetProjections$Params, context?: HttpContext): Observable<StrictHttpResponse<ProjectionResponse>> {
  const rb = new RequestBuilder(rootUrl, getProjections.PATH, 'get');
  if (params) {
    rb.query('months', params.months, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ProjectionResponse>;
    })
  );
}

getProjections.PATH = '/api/future-events/projections';
