/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { FutureEventUpdateRequest } from '../../models/future-event-update-request';
import { FutureEventResponse } from '../../models/future-event-response';

export interface UpdateFutureEvent$Params {
  id: string;
  body: FutureEventUpdateRequest;
}

export function updateFutureEvent(http: HttpClient, rootUrl: string, params: UpdateFutureEvent$Params, context?: HttpContext): Observable<StrictHttpResponse<FutureEventResponse>> {
  const rb = new RequestBuilder(rootUrl, updateFutureEvent.PATH, 'put');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<FutureEventResponse>;
    })
  );
}

updateFutureEvent.PATH = '/api/future-events/{id}';
