/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Request body for updating an account
 */
export interface AccountUpdateRequest {

  /**
   * Name of the account
   */
  name: string;

  /**
   * Type of account
   */
  type: 'CASH' | 'BANK' | 'CARD';
}
