/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Authentication response containing JWT token and user details
 */
export interface AuthResponse {

  /**
   * Display name of the user
   */
  displayName?: string;

  /**
   * Unique identifier of the user's household
   */
  householdId?: string;

  /**
   * Role of the user within the household
   */
  role?: 'USER' | 'ADMIN';

  /**
   * JWT Bearer token for authentication
   */
  token?: string;

  /**
   * Unique identifier of the user
   */
  userId?: string;
}
