/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Request body for updating a category
 */
export interface CategoryUpdateRequest {

  /**
   * Color code for the category
   */
  color?: string;

  /**
   * Icon identifier for the category
   */
  icon?: string;

  /**
   * Name of the category
   */
  name: string;
}
