/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ClassificationSuggestion } from '../models/classification-suggestion';

/**
 * Classification suggestions response
 */
export interface ClassificationSuggestResponse {

  /**
   * List of suggestions, one per input transaction
   */
  suggestions?: Array<ClassificationSuggestion>;
}
