/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Classification suggestion for a transaction
 */
export interface ClassificationSuggestion {

  /**
   * Suggested category ID (null if no match)
   */
  categoryId?: string;

  /**
   * Confidence score (0-100)
   */
  confidence?: number;

  /**
   * Confidence label
   */
  confidenceLabel?: 'HIGH' | 'MEDIUM' | 'LOW';

  /**
   * ID of the rule that matched (if any)
   */
  ruleId?: string;
}
