/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { TransactionToClassify } from '../models/transaction-to-classify';

/**
 * Request body for classification suggestions
 */
export interface ClassificationSuggestRequest {

  /**
   * List of transactions to classify
   */
  transactions: Array<TransactionToClassify>;
}
