/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Request body for creating a new classification rule
 */
export interface ClassificationRuleCreateRequest {

  /**
   * Target category ID
   */
  categoryId: string;

  /**
   * Confidence score for this rule (0-100)
   */
  confidence?: number;

  /**
   * Whether the rule is enabled
   */
  enabled?: boolean;

  /**
   * Field to match against
   */
  field: 'MERCHANT' | 'COMMUNICATION' | 'IBAN';

  /**
   * Type of pattern matching
   */
  matchType: 'CONTAINS' | 'STARTS_WITH' | 'REGEX';

  /**
   * Pattern to match
   */
  pattern: string;

  /**
   * Rule priority (higher = evaluated first)
   */
  priority?: number;
}
