/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Classification rule response data
 */
export interface ClassificationRuleResponse {

  /**
   * Target category ID
   */
  categoryId?: string;

  /**
   * Target category name
   */
  categoryName?: string;

  /**
   * Confidence score for this rule (0-100)
   */
  confidence?: number;

  /**
   * Timestamp when the rule was created
   */
  createdAt?: string;

  /**
   * Whether the rule is enabled
   */
  enabled?: boolean;

  /**
   * Field to match against
   */
  field?: 'MERCHANT' | 'COMMUNICATION' | 'IBAN';

  /**
   * Unique identifier of the rule
   */
  id?: string;

  /**
   * Type of pattern matching
   */
  matchType?: 'CONTAINS' | 'STARTS_WITH' | 'REGEX';

  /**
   * Pattern to match
   */
  pattern?: string;

  /**
   * Rule priority (higher = evaluated first)
   */
  priority?: number;

  /**
   * Source of the rule (USER or AUTO)
   */
  source?: 'USER' | 'AUTO';

  /**
   * Timestamp when the rule was last updated
   */
  updatedAt?: string;
}
