/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Current authenticated user information
 */
export interface CurrentUserResponse {

  /**
   * User's display name
   */
  displayName?: string;

  /**
   * User's email address
   */
  email?: string;

  /**
   * Unique identifier of the user's household
   */
  householdId?: string;

  /**
   * User's role within the household
   */
  role?: 'USER' | 'ADMIN';

  /**
   * Unique identifier of the user
   */
  userId?: string;
}
