/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CategoryExpenseResponse } from '../models/category-expense-response';

/**
 * Monthly dashboard aggregations including income, expenses, and category breakdown
 */
export interface DashboardResponse {

  /**
   * Breakdown of expenses by category
   */
  expensesByCategory?: Array<CategoryExpenseResponse>;

  /**
   * Month in YYYY-MM format
   */
  month?: string;

  /**
   * Net balance in cents (income - expenses)
   */
  netCents?: number;

  /**
   * Total expenses in cents for the month
   */
  totalExpenseCents?: number;

  /**
   * Total income in cents for the month
   */
  totalIncomeCents?: number;
}
