/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Future event response
 */
export interface FutureEventResponse {

  /**
   * Amount in cents
   */
  amountCents?: number;

  /**
   * End date of the recurring event (optional)
   */
  endDate?: string;

  /**
   * UUID of the event
   */
  id?: string;

  /**
   * Name of the event
   */
  name?: string;

  /**
   * Recurrence periodicity
   */
  periodicity?: string;

  /**
   * Start date of the recurring event
   */
  startDate?: string;

  /**
   * Transaction type
   */
  type?: string;
}
