/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Request to create a new future event
 */
export interface FutureEventCreateRequest {

  /**
   * Amount in cents
   */
  amountCents: number;

  /**
   * End date of the recurring event (optional)
   */
  endDate?: string;

  /**
   * Name of the event
   */
  name: string;

  /**
   * Recurrence periodicity
   */
  periodicity: string;

  /**
   * Start date of the recurring event
   */
  startDate: string;

  /**
   * Transaction type
   */
  type: string;
}
