/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Response containing keys of transactions that already exist
 */
export interface ImportCheckResponse {

  /**
   * List of deduplication keys that already exist in the database
   */
  existingKeys?: Array<string>;
}
