/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ImportTransactionItem } from '../models/import-transaction-item';

/**
 * Request body for bulk importing transactions
 */
export interface ImportTransactionRequest {

  /**
   * UUID of the target account for all imported transactions
   */
  accountId: string;

  /**
   * List of transactions to import
   */
  items: Array<ImportTransactionItem>;
}
