/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Single transaction item for bulk import
 */
export interface ImportTransactionItem {

  /**
   * Amount in cents (must be positive)
   */
  amountCents: number;

  /**
   * UUID of the category (optional for import)
   */
  categoryId?: string;

  /**
   * Counterparty IBAN if available
   */
  counterpartyIban?: string;

  /**
   * External reference ID from bank (for deduplication)
   */
  externalId?: string;

  /**
   * Merchant/counterparty name
   */
  merchant?: string;

  /**
   * Additional note/communication from bank statement
   */
  note?: string;

  /**
   * Date of the transaction
   */
  txDate: string;

  /**
   * Type of transaction
   */
  type: 'EXPENSE' | 'INCOME';
}
