/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Error details for a failed import item
 */
export interface ImportError {

  /**
   * Zero-based index of the item in the request
   */
  index?: number;

  /**
   * Error message describing why the import failed
   */
  message?: string;
}
