/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Request body for checking existing transactions before import
 */
export interface ImportCheckRequest {

  /**
   * UUID of the target account
   */
  accountId: string;

  /**
   * Start date of the period to check (inclusive)
   */
  from: string;

  /**
   * List of deduplication keys to check (format: DATE|AMOUNT|MERCHANT)
   */
  keys: Array<string>;

  /**
   * End date of the period to check (inclusive)
   */
  to: string;
}
