/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Response for initialize defaults operation
 */
export interface InitializeDefaultsResponse {

  /**
   * Status message
   */
  message?: string;

  /**
   * Number of rules created
   */
  rulesCreated?: number;

  /**
   * Whether the operation was successful
   */
  success?: boolean;
}
