/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Request body for user login
 */
export interface LoginRequest {

  /**
   * User's email address
   */
  email: string;

  /**
   * User's password
   */
  password: string;
}
