/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Single data point in budget projection
 */
export interface ProjectionDataPoint {

  /**
   * Date of this data point
   */
  date?: string;

  /**
   * Projected balance in cents at this date
   */
  projectedBalanceCents?: number;

  /**
   * Projected total expenses in cents for this period
   */
  projectedExpenseCents?: number;

  /**
   * Projected total income in cents for this period
   */
  projectedIncomeCents?: number;
}
