/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ProjectionDataPoint } from '../models/projection-data-point';

/**
 * Budget projection response with projected balances over time
 */
export interface ProjectionResponse {

  /**
   * Monthly projection data points
   */
  dataPoints?: Array<ProjectionDataPoint>;

  /**
   * End date of the projection period
   */
  endDate?: string;

  /**
   * Projected balance in cents at projection end
   */
  finalBalanceCents?: number;

  /**
   * Initial balance in cents at projection start
   */
  initialBalanceCents?: number;

  /**
   * Start date of the projection period
   */
  startDate?: string;
}
