/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

/**
 * Details of a classification rule
 */
export interface RuleDetail {

  /**
   * Rule ID
   */
  id?: string;

  /**
   * Merchant pattern
   */
  pattern?: string;

  /**
   * Category name
   */
  categoryName?: string;

  /**
   * Action taken (CREATED or UPDATED)
   */
  action?: string;

  /**
   * Confidence score
   */
  confidence?: number;
}
