/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Transaction data for classification suggestion
 */
export interface TransactionToClassify {

  /**
   * Transaction amount in cents
   */
  amount?: number;

  /**
   * Communication/description
   */
  communication?: string;

  /**
   * Transaction date
   */
  date?: string;

  /**
   * Counterparty IBAN
   */
  iban?: string;

  /**
   * Merchant name
   */
  merchant?: string;
}
