/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Request body for updating a transaction
 */
export interface TransactionUpdateRequest {

  /**
   * UUID of the account
   */
  accountId: string;

  /**
   * Amount in cents (must be positive)
   */
  amountCents: number;

  /**
   * UUID of the category
   */
  categoryId: string;

  /**
   * Merchant name
   */
  merchant?: string;

  /**
   * Additional note for the transaction
   */
  note?: string;

  /**
   * Date of the transaction
   */
  txDate: string;

  /**
   * Type of transaction
   */
  type: 'EXPENSE' | 'INCOME';
}
