/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ClassificationRuleCreateRequest } from '../../models/classification-rule-create-request';
import { ClassificationRuleResponse } from '../../models/classification-rule-response';

export interface CreateRule$Params {
      body: ClassificationRuleCreateRequest
}

export function createRule(http: HttpClient, rootUrl: string, params: CreateRule$Params, context?: HttpContext): Observable<StrictHttpResponse<ClassificationRuleResponse>> {
  const rb = new RequestBuilder(rootUrl, createRule.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ClassificationRuleResponse>;
    })
  );
}

createRule.PATH = '/api/classification-rules';
