/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ClassificationRuleResponse } from '../../models/classification-rule-response';

export interface GetAllRules$Params {
}

export function getAllRules(http: HttpClient, rootUrl: string, params?: GetAllRules$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ClassificationRuleResponse>>> {
  const rb = new RequestBuilder(rootUrl, getAllRules.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<ClassificationRuleResponse>>;
    })
  );
}

getAllRules.PATH = '/api/classification-rules';
