/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ClassificationRuleResponse } from '../../models/classification-rule-response';

export interface GetRuleById$Params {
  id: string;
}

export function getRuleById(http: HttpClient, rootUrl: string, params: GetRuleById$Params, context?: HttpContext): Observable<StrictHttpResponse<ClassificationRuleResponse>> {
  const rb = new RequestBuilder(rootUrl, getRuleById.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ClassificationRuleResponse>;
    })
  );
}

getRuleById.PATH = '/api/classification-rules/{id}';
