/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { InitializeDefaultsResponse } from '../../models/initialize-defaults-response';

export interface InitializeDefaults$Params {
}

export function initializeDefaults(http: HttpClient, rootUrl: string, params?: InitializeDefaults$Params, context?: HttpContext): Observable<StrictHttpResponse<InitializeDefaultsResponse>> {
  const rb = new RequestBuilder(rootUrl, initializeDefaults.PATH, 'post');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<InitializeDefaultsResponse>;
    })
  );
}

initializeDefaults.PATH = '/api/classification-rules/initialize-defaults';
