/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ClassificationRuleResponse } from '../../models/classification-rule-response';
import { ClassificationRuleUpdateRequest } from '../../models/classification-rule-update-request';

export interface UpdateRule$Params {
  id: string;
      body: ClassificationRuleUpdateRequest
}

export function updateRule(http: HttpClient, rootUrl: string, params: UpdateRule$Params, context?: HttpContext): Observable<StrictHttpResponse<ClassificationRuleResponse>> {
  const rb = new RequestBuilder(rootUrl, updateRule.PATH, 'put');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ClassificationRuleResponse>;
    })
  );
}

updateRule.PATH = '/api/classification-rules/{id}';
