/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DashboardResponse } from '../../models/dashboard-response';

export interface GetMonthlyDashboard$Params {

/**
 * Month in YYYY-MM format
 */
  month: string;
}

export function getMonthlyDashboard(http: HttpClient, rootUrl: string, params: GetMonthlyDashboard$Params, context?: HttpContext): Observable<StrictHttpResponse<DashboardResponse>> {
  const rb = new RequestBuilder(rootUrl, getMonthlyDashboard.PATH, 'get');
  if (params) {
    rb.query('month', params.month, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<DashboardResponse>;
    })
  );
}

getMonthlyDashboard.PATH = '/api/dashboard';
