/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { firstValueFrom } from 'rxjs';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { AccountResponse } from '../models/account-response';
import { createAccount } from '../fn/accounts/create-account';
import { CreateAccount$Params } from '../fn/accounts/create-account';
import { deleteAccount } from '../fn/accounts/delete-account';
import { DeleteAccount$Params } from '../fn/accounts/delete-account';
import { getAccountById } from '../fn/accounts/get-account-by-id';
import { GetAccountById$Params } from '../fn/accounts/get-account-by-id';
import { getAllAccounts } from '../fn/accounts/get-all-accounts';
import { GetAllAccounts$Params } from '../fn/accounts/get-all-accounts';
import { updateAccount } from '../fn/accounts/update-account';
import { UpdateAccount$Params } from '../fn/accounts/update-account';


/**
 * Account management endpoints
 */
@Injectable({ providedIn: 'root' })
export class AccountsService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getAccountById()` */
  static readonly GetAccountByIdPath = '/api/accounts/{id}';

  /**
   * Get account by ID.
   *
   * Returns an account by its ID for the current user's household
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAccountById()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAccountById$Response(params: GetAccountById$Params, context?: HttpContext): Promise<StrictHttpResponse<AccountResponse>> {
    const obs = getAccountById(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Get account by ID.
   *
   * Returns an account by its ID for the current user's household
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAccountById$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAccountById(params: GetAccountById$Params, context?: HttpContext): Promise<AccountResponse> {
    const resp = this.getAccountById$Response(params, context);
    return resp.then((r: StrictHttpResponse<AccountResponse>): AccountResponse => r.body);
  }

  /** Path part for operation `updateAccount()` */
  static readonly UpdateAccountPath = '/api/accounts/{id}';

  /**
   * Update an account.
   *
   * Updates an existing account for the current user's household
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updateAccount()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateAccount$Response(params: UpdateAccount$Params, context?: HttpContext): Promise<StrictHttpResponse<AccountResponse>> {
    const obs = updateAccount(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Update an account.
   *
   * Updates an existing account for the current user's household
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updateAccount$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateAccount(params: UpdateAccount$Params, context?: HttpContext): Promise<AccountResponse> {
    const resp = this.updateAccount$Response(params, context);
    return resp.then((r: StrictHttpResponse<AccountResponse>): AccountResponse => r.body);
  }

  /** Path part for operation `deleteAccount()` */
  static readonly DeleteAccountPath = '/api/accounts/{id}';

  /**
   * Delete an account.
   *
   * Deletes an account for the current user's household
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `deleteAccount()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteAccount$Response(params: DeleteAccount$Params, context?: HttpContext): Promise<StrictHttpResponse<void>> {
    const obs = deleteAccount(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Delete an account.
   *
   * Deletes an account for the current user's household
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `deleteAccount$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteAccount(params: DeleteAccount$Params, context?: HttpContext): Promise<void> {
    const resp = this.deleteAccount$Response(params, context);
    return resp.then((r: StrictHttpResponse<void>): void => r.body);
  }

  /** Path part for operation `getAllAccounts()` */
  static readonly GetAllAccountsPath = '/api/accounts';

  /**
   * Get all accounts.
   *
   * Returns all accounts for the current user's household
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAllAccounts()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllAccounts$Response(params?: GetAllAccounts$Params, context?: HttpContext): Promise<StrictHttpResponse<Array<AccountResponse>>> {
    const obs = getAllAccounts(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Get all accounts.
   *
   * Returns all accounts for the current user's household
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAllAccounts$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllAccounts(params?: GetAllAccounts$Params, context?: HttpContext): Promise<Array<AccountResponse>> {
    const resp = this.getAllAccounts$Response(params, context);
    return resp.then((r: StrictHttpResponse<Array<AccountResponse>>): Array<AccountResponse> => r.body);
  }

  /** Path part for operation `createAccount()` */
  static readonly CreateAccountPath = '/api/accounts';

  /**
   * Create a new account.
   *
   * Creates a new account for the current user's household
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `createAccount()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createAccount$Response(params: CreateAccount$Params, context?: HttpContext): Promise<StrictHttpResponse<AccountResponse>> {
    const obs = createAccount(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Create a new account.
   *
   * Creates a new account for the current user's household
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `createAccount$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createAccount(params: CreateAccount$Params, context?: HttpContext): Promise<AccountResponse> {
    const resp = this.createAccount$Response(params, context);
    return resp.then((r: StrictHttpResponse<AccountResponse>): AccountResponse => r.body);
  }

}
