/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { firstValueFrom } from 'rxjs';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { CategoryResponse } from '../models/category-response';
import { createCategory } from '../fn/categories/create-category';
import { CreateCategory$Params } from '../fn/categories/create-category';
import { deleteCategory } from '../fn/categories/delete-category';
import { DeleteCategory$Params } from '../fn/categories/delete-category';
import { getAllCategories } from '../fn/categories/get-all-categories';
import { GetAllCategories$Params } from '../fn/categories/get-all-categories';
import { getCategoryById } from '../fn/categories/get-category-by-id';
import { GetCategoryById$Params } from '../fn/categories/get-category-by-id';
import { updateCategory } from '../fn/categories/update-category';
import { UpdateCategory$Params } from '../fn/categories/update-category';


/**
 * Category management endpoints
 */
@Injectable({ providedIn: 'root' })
export class CategoriesService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getCategoryById()` */
  static readonly GetCategoryByIdPath = '/api/categories/{id}';

  /**
   * Get category by ID.
   *
   * Returns a category by its ID for the current user's household
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getCategoryById()` instead.
   *
   * This method doesn't expect any request body.
   */
  getCategoryById$Response(params: GetCategoryById$Params, context?: HttpContext): Promise<StrictHttpResponse<CategoryResponse>> {
    const obs = getCategoryById(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Get category by ID.
   *
   * Returns a category by its ID for the current user's household
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getCategoryById$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getCategoryById(params: GetCategoryById$Params, context?: HttpContext): Promise<CategoryResponse> {
    const resp = this.getCategoryById$Response(params, context);
    return resp.then((r: StrictHttpResponse<CategoryResponse>): CategoryResponse => r.body);
  }

  /** Path part for operation `updateCategory()` */
  static readonly UpdateCategoryPath = '/api/categories/{id}';

  /**
   * Update a category.
   *
   * Updates an existing category for the current user's household
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updateCategory()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateCategory$Response(params: UpdateCategory$Params, context?: HttpContext): Promise<StrictHttpResponse<CategoryResponse>> {
    const obs = updateCategory(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Update a category.
   *
   * Updates an existing category for the current user's household
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updateCategory$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateCategory(params: UpdateCategory$Params, context?: HttpContext): Promise<CategoryResponse> {
    const resp = this.updateCategory$Response(params, context);
    return resp.then((r: StrictHttpResponse<CategoryResponse>): CategoryResponse => r.body);
  }

  /** Path part for operation `deleteCategory()` */
  static readonly DeleteCategoryPath = '/api/categories/{id}';

  /**
   * Delete a category.
   *
   * Deletes a category for the current user's household
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `deleteCategory()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteCategory$Response(params: DeleteCategory$Params, context?: HttpContext): Promise<StrictHttpResponse<void>> {
    const obs = deleteCategory(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Delete a category.
   *
   * Deletes a category for the current user's household
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `deleteCategory$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteCategory(params: DeleteCategory$Params, context?: HttpContext): Promise<void> {
    const resp = this.deleteCategory$Response(params, context);
    return resp.then((r: StrictHttpResponse<void>): void => r.body);
  }

  /** Path part for operation `getAllCategories()` */
  static readonly GetAllCategoriesPath = '/api/categories';

  /**
   * Get all categories.
   *
   * Returns all categories for the current user's household
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAllCategories()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllCategories$Response(params?: GetAllCategories$Params, context?: HttpContext): Promise<StrictHttpResponse<Array<CategoryResponse>>> {
    const obs = getAllCategories(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Get all categories.
   *
   * Returns all categories for the current user's household
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAllCategories$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllCategories(params?: GetAllCategories$Params, context?: HttpContext): Promise<Array<CategoryResponse>> {
    const resp = this.getAllCategories$Response(params, context);
    return resp.then((r: StrictHttpResponse<Array<CategoryResponse>>): Array<CategoryResponse> => r.body);
  }

  /** Path part for operation `createCategory()` */
  static readonly CreateCategoryPath = '/api/categories';

  /**
   * Create a new category.
   *
   * Creates a new category for the current user's household
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `createCategory()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createCategory$Response(params: CreateCategory$Params, context?: HttpContext): Promise<StrictHttpResponse<CategoryResponse>> {
    const obs = createCategory(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Create a new category.
   *
   * Creates a new category for the current user's household
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `createCategory$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createCategory(params: CreateCategory$Params, context?: HttpContext): Promise<CategoryResponse> {
    const resp = this.createCategory$Response(params, context);
    return resp.then((r: StrictHttpResponse<CategoryResponse>): CategoryResponse => r.body);
  }

}
