/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { firstValueFrom } from 'rxjs';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { ClassificationRuleResponse } from '../models/classification-rule-response';
import { createRule } from '../fn/classification-rules/create-rule';
import { CreateRule$Params } from '../fn/classification-rules/create-rule';
import { deleteRule } from '../fn/classification-rules/delete-rule';
import { DeleteRule$Params } from '../fn/classification-rules/delete-rule';
import { getAllRules } from '../fn/classification-rules/get-all-rules';
import { GetAllRules$Params } from '../fn/classification-rules/get-all-rules';
import { getRuleById } from '../fn/classification-rules/get-rule-by-id';
import { GetRuleById$Params } from '../fn/classification-rules/get-rule-by-id';
import { initializeDefaultRules } from '../fn/classification-rules/initialize-default-rules';
import { InitializeDefaultRules$Params } from '../fn/classification-rules/initialize-default-rules';
import { updateRule } from '../fn/classification-rules/update-rule';
import { UpdateRule$Params } from '../fn/classification-rules/update-rule';


/**
 * CRUD endpoints for classification rules
 */
@Injectable({ providedIn: 'root' })
export class ClassificationRulesService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getRuleById()` */
  static readonly GetRuleByIdPath = '/api/classification-rules/{id}';

  /**
   * Get classification rule by ID.
   *
   * Returns a classification rule by its ID for the current user's household
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getRuleById()` instead.
   *
   * This method doesn't expect any request body.
   */
  getRuleById$Response(params: GetRuleById$Params, context?: HttpContext): Promise<StrictHttpResponse<ClassificationRuleResponse>> {
    const obs = getRuleById(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Get classification rule by ID.
   *
   * Returns a classification rule by its ID for the current user's household
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getRuleById$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getRuleById(params: GetRuleById$Params, context?: HttpContext): Promise<ClassificationRuleResponse> {
    const resp = this.getRuleById$Response(params, context);
    return resp.then((r: StrictHttpResponse<ClassificationRuleResponse>): ClassificationRuleResponse => r.body);
  }

  /** Path part for operation `updateRule()` */
  static readonly UpdateRulePath = '/api/classification-rules/{id}';

  /**
   * Update a classification rule.
   *
   * Updates an existing classification rule for the current user's household
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updateRule()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateRule$Response(params: UpdateRule$Params, context?: HttpContext): Promise<StrictHttpResponse<ClassificationRuleResponse>> {
    const obs = updateRule(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Update a classification rule.
   *
   * Updates an existing classification rule for the current user's household
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updateRule$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateRule(params: UpdateRule$Params, context?: HttpContext): Promise<ClassificationRuleResponse> {
    const resp = this.updateRule$Response(params, context);
    return resp.then((r: StrictHttpResponse<ClassificationRuleResponse>): ClassificationRuleResponse => r.body);
  }

  /** Path part for operation `deleteRule()` */
  static readonly DeleteRulePath = '/api/classification-rules/{id}';

  /**
   * Delete a classification rule.
   *
   * Deletes a classification rule for the current user's household
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `deleteRule()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteRule$Response(params: DeleteRule$Params, context?: HttpContext): Promise<StrictHttpResponse<void>> {
    const obs = deleteRule(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Delete a classification rule.
   *
   * Deletes a classification rule for the current user's household
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `deleteRule$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteRule(params: DeleteRule$Params, context?: HttpContext): Promise<void> {
    const resp = this.deleteRule$Response(params, context);
    return resp.then((r: StrictHttpResponse<void>): void => r.body);
  }

  /** Path part for operation `getAllRules()` */
  static readonly GetAllRulesPath = '/api/classification-rules';

  /**
   * Get all classification rules.
   *
   * Returns all classification rules for the current user's household
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAllRules()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllRules$Response(params?: GetAllRules$Params, context?: HttpContext): Promise<StrictHttpResponse<Array<ClassificationRuleResponse>>> {
    const obs = getAllRules(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Get all classification rules.
   *
   * Returns all classification rules for the current user's household
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAllRules$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllRules(params?: GetAllRules$Params, context?: HttpContext): Promise<Array<ClassificationRuleResponse>> {
    const resp = this.getAllRules$Response(params, context);
    return resp.then((r: StrictHttpResponse<Array<ClassificationRuleResponse>>): Array<ClassificationRuleResponse> => r.body);
  }

  /** Path part for operation `createRule()` */
  static readonly CreateRulePath = '/api/classification-rules';

  /**
   * Create a new classification rule.
   *
   * Creates a new classification rule for the current user's household
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `createRule()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createRule$Response(params: CreateRule$Params, context?: HttpContext): Promise<StrictHttpResponse<ClassificationRuleResponse>> {
    const obs = createRule(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Create a new classification rule.
   *
   * Creates a new classification rule for the current user's household
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `createRule$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createRule(params: CreateRule$Params, context?: HttpContext): Promise<ClassificationRuleResponse> {
    const resp = this.createRule$Response(params, context);
    return resp.then((r: StrictHttpResponse<ClassificationRuleResponse>): ClassificationRuleResponse => r.body);
  }

  /** Path part for operation `initializeDefaultRules()` */
  static readonly InitializeDefaultRulesPath = '/api/classification-rules/initialize-defaults';

  /**
   * Initialize default classification rules.
   *
   * Creates default classification rules for the current user's household if none exist. This is useful for existing users who registered before the auto-categorization feature was added.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `initializeDefaultRules()` instead.
   *
   * This method doesn't expect any request body.
   */
  initializeDefaultRules$Response(params?: InitializeDefaultRules$Params, context?: HttpContext): Promise<StrictHttpResponse<{
[key: string]: any;
}>> {
    const obs = initializeDefaultRules(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Initialize default classification rules.
   *
   * Creates default classification rules for the current user's household if none exist. This is useful for existing users who registered before the auto-categorization feature was added.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `initializeDefaultRules$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  initializeDefaultRules(params?: InitializeDefaultRules$Params, context?: HttpContext): Promise<{
[key: string]: any;
}> {
    const resp = this.initializeDefaultRules$Response(params, context);
    return resp.then((r: StrictHttpResponse<{
[key: string]: any;
}>): {
[key: string]: any;
} => r.body);
  }

}
