/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { firstValueFrom } from 'rxjs';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { DashboardResponse } from '../models/dashboard-response';
import { getMonthlyDashboard } from '../fn/dashboard/get-monthly-dashboard';
import { GetMonthlyDashboard$Params } from '../fn/dashboard/get-monthly-dashboard';


/**
 * Dashboard endpoints for monthly aggregations and statistics
 */
@Injectable({ providedIn: 'root' })
export class DashboardService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getMonthlyDashboard()` */
  static readonly GetMonthlyDashboardPath = '/api/dashboard';

  /**
   * Get monthly dashboard.
   *
   * Returns monthly aggregations including total income, total expenses, net balance, and expense breakdown by category for the current user's household.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getMonthlyDashboard()` instead.
   *
   * This method doesn't expect any request body.
   */
  getMonthlyDashboard$Response(params: GetMonthlyDashboard$Params, context?: HttpContext): Promise<StrictHttpResponse<DashboardResponse>> {
    const obs = getMonthlyDashboard(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Get monthly dashboard.
   *
   * Returns monthly aggregations including total income, total expenses, net balance, and expense breakdown by category for the current user's household.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getMonthlyDashboard$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getMonthlyDashboard(params: GetMonthlyDashboard$Params, context?: HttpContext): Promise<DashboardResponse> {
    const resp = this.getMonthlyDashboard$Response(params, context);
    return resp.then((r: StrictHttpResponse<DashboardResponse>): DashboardResponse => r.body);
  }

}
