/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { firstValueFrom } from 'rxjs';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { createFutureEvent } from '../fn/future-events/create-future-event';
import { CreateFutureEvent$Params } from '../fn/future-events/create-future-event';
import { deleteFutureEvent } from '../fn/future-events/delete-future-event';
import { DeleteFutureEvent$Params } from '../fn/future-events/delete-future-event';
import { FutureEventResponse } from '../models/future-event-response';
import { getAllFutureEvents } from '../fn/future-events/get-all-future-events';
import { GetAllFutureEvents$Params } from '../fn/future-events/get-all-future-events';
import { getFutureEvent } from '../fn/future-events/get-future-event';
import { GetFutureEvent$Params } from '../fn/future-events/get-future-event';
import { getProjections } from '../fn/future-events/get-projections';
import { GetProjections$Params } from '../fn/future-events/get-projections';
import { ProjectionResponse } from '../models/projection-response';
import { updateFutureEvent } from '../fn/future-events/update-future-event';
import { UpdateFutureEvent$Params } from '../fn/future-events/update-future-event';


/**
 * Manage recurring future events and budget projections
 */
@Injectable({ providedIn: 'root' })
export class FutureEventsService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getFutureEvent()` */
  static readonly GetFutureEventPath = '/api/future-events/{id}';

  /**
   * Get a future event.
   *
   * Returns a specific future event by ID.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getFutureEvent()` instead.
   *
   * This method doesn't expect any request body.
   */
  getFutureEvent$Response(params: GetFutureEvent$Params, context?: HttpContext): Promise<StrictHttpResponse<FutureEventResponse>> {
    const obs = getFutureEvent(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Get a future event.
   *
   * Returns a specific future event by ID.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getFutureEvent$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getFutureEvent(params: GetFutureEvent$Params, context?: HttpContext): Promise<FutureEventResponse> {
    const resp = this.getFutureEvent$Response(params, context);
    return resp.then((r: StrictHttpResponse<FutureEventResponse>): FutureEventResponse => r.body);
  }

  /** Path part for operation `updateFutureEvent()` */
  static readonly UpdateFutureEventPath = '/api/future-events/{id}';

  /**
   * Update a future event.
   *
   * Updates an existing future event.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updateFutureEvent()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateFutureEvent$Response(params: UpdateFutureEvent$Params, context?: HttpContext): Promise<StrictHttpResponse<FutureEventResponse>> {
    const obs = updateFutureEvent(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Update a future event.
   *
   * Updates an existing future event.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updateFutureEvent$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateFutureEvent(params: UpdateFutureEvent$Params, context?: HttpContext): Promise<FutureEventResponse> {
    const resp = this.updateFutureEvent$Response(params, context);
    return resp.then((r: StrictHttpResponse<FutureEventResponse>): FutureEventResponse => r.body);
  }

  /** Path part for operation `deleteFutureEvent()` */
  static readonly DeleteFutureEventPath = '/api/future-events/{id}';

  /**
   * Delete a future event.
   *
   * Deletes a future event.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `deleteFutureEvent()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteFutureEvent$Response(params: DeleteFutureEvent$Params, context?: HttpContext): Promise<StrictHttpResponse<void>> {
    const obs = deleteFutureEvent(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Delete a future event.
   *
   * Deletes a future event.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `deleteFutureEvent$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteFutureEvent(params: DeleteFutureEvent$Params, context?: HttpContext): Promise<void> {
    const resp = this.deleteFutureEvent$Response(params, context);
    return resp.then((r: StrictHttpResponse<void>): void => r.body);
  }

  /** Path part for operation `getAllFutureEvents()` */
  static readonly GetAllFutureEventsPath = '/api/future-events';

  /**
   * Get all future events.
   *
   * Returns all future events for the current user's household.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAllFutureEvents()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllFutureEvents$Response(params?: GetAllFutureEvents$Params, context?: HttpContext): Promise<StrictHttpResponse<Array<FutureEventResponse>>> {
    const obs = getAllFutureEvents(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Get all future events.
   *
   * Returns all future events for the current user's household.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAllFutureEvents$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllFutureEvents(params?: GetAllFutureEvents$Params, context?: HttpContext): Promise<Array<FutureEventResponse>> {
    const resp = this.getAllFutureEvents$Response(params, context);
    return resp.then((r: StrictHttpResponse<Array<FutureEventResponse>>): Array<FutureEventResponse> => r.body);
  }

  /** Path part for operation `createFutureEvent()` */
  static readonly CreateFutureEventPath = '/api/future-events';

  /**
   * Create a future event.
   *
   * Creates a new recurring future event (subscription, regular payment, etc.).
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `createFutureEvent()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createFutureEvent$Response(params: CreateFutureEvent$Params, context?: HttpContext): Promise<StrictHttpResponse<FutureEventResponse>> {
    const obs = createFutureEvent(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Create a future event.
   *
   * Creates a new recurring future event (subscription, regular payment, etc.).
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `createFutureEvent$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createFutureEvent(params: CreateFutureEvent$Params, context?: HttpContext): Promise<FutureEventResponse> {
    const resp = this.createFutureEvent$Response(params, context);
    return resp.then((r: StrictHttpResponse<FutureEventResponse>): FutureEventResponse => r.body);
  }

  /** Path part for operation `getProjections()` */
  static readonly GetProjectionsPath = '/api/future-events/projections';

  /**
   * Get budget projections.
   *
   * Returns projected budget data based on future events for 1-12 months.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getProjections()` instead.
   *
   * This method doesn't expect any request body.
   */
  getProjections$Response(params?: GetProjections$Params, context?: HttpContext): Promise<StrictHttpResponse<ProjectionResponse>> {
    const obs = getProjections(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Get budget projections.
   *
   * Returns projected budget data based on future events for 1-12 months.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getProjections$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getProjections(params?: GetProjections$Params, context?: HttpContext): Promise<ProjectionResponse> {
    const resp = this.getProjections$Response(params, context);
    return resp.then((r: StrictHttpResponse<ProjectionResponse>): ProjectionResponse => r.body);
  }

}
