/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { firstValueFrom } from 'rxjs';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { createTransaction } from '../fn/transactions/create-transaction';
import { CreateTransaction$Params } from '../fn/transactions/create-transaction';
import { deleteTransaction } from '../fn/transactions/delete-transaction';
import { DeleteTransaction$Params } from '../fn/transactions/delete-transaction';
import { getAllTransactions } from '../fn/transactions/get-all-transactions';
import { GetAllTransactions$Params } from '../fn/transactions/get-all-transactions';
import { getTransactionById } from '../fn/transactions/get-transaction-by-id';
import { GetTransactionById$Params } from '../fn/transactions/get-transaction-by-id';
import { TransactionResponse } from '../models/transaction-response';
import { updateTransaction } from '../fn/transactions/update-transaction';
import { UpdateTransaction$Params } from '../fn/transactions/update-transaction';


/**
 * Transaction management endpoints with filtering capabilities
 */
@Injectable({ providedIn: 'root' })
export class TransactionsService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getTransactionById()` */
  static readonly GetTransactionByIdPath = '/api/transactions/{id}';

  /**
   * Get transaction by ID.
   *
   * Returns a transaction by its ID for the current user's household
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getTransactionById()` instead.
   *
   * This method doesn't expect any request body.
   */
  getTransactionById$Response(params: GetTransactionById$Params, context?: HttpContext): Promise<StrictHttpResponse<TransactionResponse>> {
    const obs = getTransactionById(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Get transaction by ID.
   *
   * Returns a transaction by its ID for the current user's household
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getTransactionById$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getTransactionById(params: GetTransactionById$Params, context?: HttpContext): Promise<TransactionResponse> {
    const resp = this.getTransactionById$Response(params, context);
    return resp.then((r: StrictHttpResponse<TransactionResponse>): TransactionResponse => r.body);
  }

  /** Path part for operation `updateTransaction()` */
  static readonly UpdateTransactionPath = '/api/transactions/{id}';

  /**
   * Update a transaction.
   *
   * Updates an existing transaction for the current user's household. The category and account must belong to the same household.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updateTransaction()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateTransaction$Response(params: UpdateTransaction$Params, context?: HttpContext): Promise<StrictHttpResponse<TransactionResponse>> {
    const obs = updateTransaction(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Update a transaction.
   *
   * Updates an existing transaction for the current user's household. The category and account must belong to the same household.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updateTransaction$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateTransaction(params: UpdateTransaction$Params, context?: HttpContext): Promise<TransactionResponse> {
    const resp = this.updateTransaction$Response(params, context);
    return resp.then((r: StrictHttpResponse<TransactionResponse>): TransactionResponse => r.body);
  }

  /** Path part for operation `deleteTransaction()` */
  static readonly DeleteTransactionPath = '/api/transactions/{id}';

  /**
   * Delete a transaction.
   *
   * Deletes a transaction for the current user's household
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `deleteTransaction()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteTransaction$Response(params: DeleteTransaction$Params, context?: HttpContext): Promise<StrictHttpResponse<void>> {
    const obs = deleteTransaction(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Delete a transaction.
   *
   * Deletes a transaction for the current user's household
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `deleteTransaction$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteTransaction(params: DeleteTransaction$Params, context?: HttpContext): Promise<void> {
    const resp = this.deleteTransaction$Response(params, context);
    return resp.then((r: StrictHttpResponse<void>): void => r.body);
  }

  /** Path part for operation `getAllTransactions()` */
  static readonly GetAllTransactionsPath = '/api/transactions';

  /**
   * Get all transactions with optional filters.
   *
   * Returns all transactions for the current user's household. Supports optional filtering by date range, category, account, and transaction type.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAllTransactions()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllTransactions$Response(params?: GetAllTransactions$Params, context?: HttpContext): Promise<StrictHttpResponse<Array<TransactionResponse>>> {
    const obs = getAllTransactions(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Get all transactions with optional filters.
   *
   * Returns all transactions for the current user's household. Supports optional filtering by date range, category, account, and transaction type.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAllTransactions$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllTransactions(params?: GetAllTransactions$Params, context?: HttpContext): Promise<Array<TransactionResponse>> {
    const resp = this.getAllTransactions$Response(params, context);
    return resp.then((r: StrictHttpResponse<Array<TransactionResponse>>): Array<TransactionResponse> => r.body);
  }

  /** Path part for operation `createTransaction()` */
  static readonly CreateTransactionPath = '/api/transactions';

  /**
   * Create a new transaction.
   *
   * Creates a new transaction for the current user's household. The category and account must belong to the same household.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `createTransaction()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createTransaction$Response(params: CreateTransaction$Params, context?: HttpContext): Promise<StrictHttpResponse<TransactionResponse>> {
    const obs = createTransaction(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Create a new transaction.
   *
   * Creates a new transaction for the current user's household. The category and account must belong to the same household.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `createTransaction$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createTransaction(params: CreateTransaction$Params, context?: HttpContext): Promise<TransactionResponse> {
    const resp = this.createTransaction$Response(params, context);
    return resp.then((r: StrictHttpResponse<TransactionResponse>): TransactionResponse => r.body);
  }

}
