/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { firstValueFrom } from 'rxjs';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { CurrentUserResponse } from '../models/current-user-response';
import { getCurrentUser } from '../fn/user/get-current-user';
import { GetCurrentUser$Params } from '../fn/user/get-current-user';


/**
 * User information endpoints
 */
@Injectable({ providedIn: 'root' })
export class UserService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getCurrentUser()` */
  static readonly GetCurrentUserPath = '/api/me';

  /**
   * Get current user info.
   *
   * Returns the current authenticated user's information including householdId and role
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getCurrentUser()` instead.
   *
   * This method doesn't expect any request body.
   */
  getCurrentUser$Response(params?: GetCurrentUser$Params, context?: HttpContext): Promise<StrictHttpResponse<CurrentUserResponse>> {
    const obs = getCurrentUser(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Get current user info.
   *
   * Returns the current authenticated user's information including householdId and role
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getCurrentUser$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getCurrentUser(params?: GetCurrentUser$Params, context?: HttpContext): Promise<CurrentUserResponse> {
    const resp = this.getCurrentUser$Response(params, context);
    return resp.then((r: StrictHttpResponse<CurrentUserResponse>): CurrentUserResponse => r.body);
  }

}
