/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TransactionCreateRequest } from '../../models/transaction-create-request';
import { TransactionResponse } from '../../models/transaction-response';

export interface CreateTransaction$Params {
      body: TransactionCreateRequest
}

export function createTransaction(http: HttpClient, rootUrl: string, params: CreateTransaction$Params, context?: HttpContext): Observable<StrictHttpResponse<TransactionResponse>> {
  const rb = new RequestBuilder(rootUrl, createTransaction.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<TransactionResponse>;
    })
  );
}

createTransaction.PATH = '/api/transactions';
