/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TransactionResponse } from '../../models/transaction-response';

export interface GetAllTransactions$Params {

/**
 * Start date (inclusive) in YYYY-MM-DD format
 */
  from?: string;

/**
 * End date (inclusive) in YYYY-MM-DD format
 */
  to?: string;

/**
 * Filter by category UUID
 */
  categoryId?: string;

/**
 * Filter by account UUID
 */
  accountId?: string;

/**
 * Filter by transaction type (EXPENSE or INCOME)
 */
  type?: 'EXPENSE' | 'INCOME';
}

export function getAllTransactions(http: HttpClient, rootUrl: string, params?: GetAllTransactions$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<TransactionResponse>>> {
  const rb = new RequestBuilder(rootUrl, getAllTransactions.PATH, 'get');
  if (params) {
    rb.query('from', params.from, {});
    rb.query('to', params.to, {});
    rb.query('categoryId', params.categoryId, {});
    rb.query('accountId', params.accountId, {});
    rb.query('type', params.type, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<TransactionResponse>>;
    })
  );
}

getAllTransactions.PATH = '/api/transactions';
