/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ImportTransactionRequest } from '../../models/import-transaction-request';
import { ImportTransactionResponse } from '../../models/import-transaction-response';

export interface ImportTransactions$Params {
      body: ImportTransactionRequest
}

export function importTransactions(http: HttpClient, rootUrl: string, params: ImportTransactions$Params, context?: HttpContext): Observable<StrictHttpResponse<ImportTransactionResponse>> {
  const rb = new RequestBuilder(rootUrl, importTransactions.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ImportTransactionResponse>;
    })
  );
}

importTransactions.PATH = '/api/transactions/import';
