/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TransactionResponse } from '../../models/transaction-response';
import { TransactionUpdateRequest } from '../../models/transaction-update-request';

export interface UpdateTransaction$Params {
  id: string;
      body: TransactionUpdateRequest
}

export function updateTransaction(http: HttpClient, rootUrl: string, params: UpdateTransaction$Params, context?: HttpContext): Observable<StrictHttpResponse<TransactionResponse>> {
  const rb = new RequestBuilder(rootUrl, updateTransaction.PATH, 'put');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<TransactionResponse>;
    })
  );
}

updateTransaction.PATH = '/api/transactions/{id}';
