/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { LearningResult } from '../../models/learning-result';

export interface Learn$Params {
}

export function learn(http: HttpClient, rootUrl: string, params?: Learn$Params, context?: HttpContext): Observable<StrictHttpResponse<LearningResult>> {
  const rb = new RequestBuilder(rootUrl, learn.PATH, 'post');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<LearningResult>;
    })
  );
}

learn.PATH = '/api/classification/learn';
