/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ClassificationSuggestRequest } from '../../models/classification-suggest-request';
import { ClassificationSuggestResponse } from '../../models/classification-suggest-response';

export interface Suggest$Params {
      body: ClassificationSuggestRequest
}

export function suggest(http: HttpClient, rootUrl: string, params: Suggest$Params, context?: HttpContext): Observable<StrictHttpResponse<ClassificationSuggestResponse>> {
  const rb = new RequestBuilder(rootUrl, suggest.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ClassificationSuggestResponse>;
    })
  );
}

suggest.PATH = '/api/classification/suggest';
